# Generated by Django 2.0.dev20170827005745 on 2017-10-03 03:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_text', models.CharField(max_length=200, verbose_name='entry title')),
                ('body_text', models.CharField(max_length=200, verbose_name='entry body')),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='published date')),
                ('hidden_boolean', models.BooleanField(default=False, verbose_name='hidden')),
                ('deleted_boolean', models.BooleanField(default=False, verbose_name='deleted')),
                ('orginal_index', models.PositiveIntegerField(default=0, verbose_name='orginal entry id')),
            ],
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(allow_unicode=True, unique=True, verbose_name='slug text')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created')),
                ('modified_date', models.DateTimeField(blank=True, null=True, verbose_name='date modified')),
                ('name_text', models.CharField(max_length=200, unique=True, verbose_name='journal name')),
                ('description_text', models.CharField(max_length=200, verbose_name='journal description')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name_text'],
            },
        ),
        migrations.AddField(
            model_name='entry',
            name='journal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journals.Journal'),
        ),
    ]
