# Generated by Django 2.0.dev20170827005745 on 2017-10-03 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='orginal_index',
        ),
        migrations.AddField(
            model_name='entry',
            name='orginal_entry',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
