# Generated by Django 2.0.dev20170827005745 on 2017-10-03 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0002_auto_20171003_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='is_replaced',
            field=models.BooleanField(default=False, verbose_name='replaced'),
        ),
    ]
