# Generated by Django 2.0.dev20170827005745 on 2017-10-03 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0003_entry_is_replaced'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='is_replaced',
        ),
        migrations.AddField(
            model_name='entry',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='replaced'),
        ),
    ]
