# Generated by Django 2.0.dev20170827005745 on 2017-10-04 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0004_auto_20171004_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='published_date',
            field=models.DateTimeField(default='04-10-2017', verbose_name='published date'),
        ),
    ]
