# Generated by Django 2.0.dev20170827005745 on 2017-10-04 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0007_auto_20171004_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='published_date',
            field=models.DateField(default='DD-MM-YYYY', verbose_name='published date'),
        ),
    ]
