# Generated by Django 2.0.dev20170827005745 on 2017-10-04 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0008_auto_20171004_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='published_date',
            field=models.DateField(default='YYYY-MM-DD', verbose_name='published date'),
        ),
    ]
